version: '3'
services:
  express:
    build: .
    ports:
    - "443:443"
    - "80:80"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
